services:
  nextjs:
    build: .
    container_name: nextjs
    env_file:
      - .env.local

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextjs
